/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConditionsGeneralesDeVenteRouteImport } from './routes/conditions-generales-de-vente'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as EspaceClientRouteImport } from './routes/espace-client'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as SurMesureRouteImport } from './routes/sur-mesure'
import { Route as CoursIndexRouteImport } from './routes/cours/index'
import { Route as CoursSlugRouteImport } from './routes/cours/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsGeneralesDeVenteRoute =
  ConditionsGeneralesDeVenteRouteImport.update({
    id: '/conditions-generales-de-vente',
    path: '/conditions-generales-de-vente',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceClientRoute = EspaceClientRouteImport.update({
  id: '/espace-client',
  path: '/espace-client',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const SurMesureRoute = SurMesureRouteImport.update({
  id: '/sur-mesure',
  path: '/sur-mesure',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursIndexRoute = CoursIndexRouteImport.update({
  id: '/cours/',
  path: '/cours/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursSlugRoute = CoursSlugRouteImport.update({
  id: '/cours/$slug',
  path: '/cours/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conditions-generales-de-vente': typeof ConditionsGeneralesDeVenteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/espace-client': typeof EspaceClientRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sur-mesure': typeof SurMesureRoute
  '/cours/$slug': typeof CoursSlugRoute
  '/cours/': typeof CoursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conditions-generales-de-vente': typeof ConditionsGeneralesDeVenteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/espace-client': typeof EspaceClientRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sur-mesure': typeof SurMesureRoute
  '/cours/$slug': typeof CoursSlugRoute
  '/cours': typeof CoursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conditions-generales-de-vente': typeof ConditionsGeneralesDeVenteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/espace-client': typeof EspaceClientRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sur-mesure': typeof SurMesureRoute
  '/cours/$slug': typeof CoursSlugRoute
  '/cours/': typeof CoursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conditions-generales-de-vente'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/espace-client'
    | '/mentions-legales'
    | '/sur-mesure'
    | '/cours/$slug'
    | '/cours/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conditions-generales-de-vente'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/espace-client'
    | '/mentions-legales'
    | '/sur-mesure'
    | '/cours/$slug'
    | '/cours'
  id:
    | '__root__'
    | '/'
    | '/conditions-generales-de-vente'
    | '/confidentialite'
    | '/contact'
    | '/cookies'
    | '/espace-client'
    | '/mentions-legales'
    | '/sur-mesure'
    | '/cours/$slug'
    | '/cours/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConditionsGeneralesDeVenteRoute: typeof ConditionsGeneralesDeVenteRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  EspaceClientRoute: typeof EspaceClientRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  SurMesureRoute: typeof SurMesureRoute
  CoursSlugRoute: typeof CoursSlugRoute
  CoursIndexRoute: typeof CoursIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-generales-de-vente': {
      id: '/conditions-generales-de-vente'
      path: '/conditions-generales-de-vente'
      fullPath: '/conditions-generales-de-vente'
      preLoaderRoute: typeof ConditionsGeneralesDeVenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-client': {
      id: '/espace-client'
      path: '/espace-client'
      fullPath: '/espace-client'
      preLoaderRoute: typeof EspaceClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sur-mesure': {
      id: '/sur-mesure'
      path: '/sur-mesure'
      fullPath: '/sur-mesure'
      preLoaderRoute: typeof SurMesureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours/': {
      id: '/cours/'
      path: '/cours'
      fullPath: '/cours/'
      preLoaderRoute: typeof CoursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours/$slug': {
      id: '/cours/$slug'
      path: '/cours/$slug'
      fullPath: '/cours/$slug'
      preLoaderRoute: typeof CoursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConditionsGeneralesDeVenteRoute: ConditionsGeneralesDeVenteRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  EspaceClientRoute: EspaceClientRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  SurMesureRoute: SurMesureRoute,
  CoursSlugRoute: CoursSlugRoute,
  CoursIndexRoute: CoursIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
